version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.12.4
    container_name: qdrant
    ports:
      - "6333:6333"    # REST
      - "6334:6334"    # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
