[project]
name = "agent-orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.11"
dependencies = [
    "anthropic>=0.52.0",
    "fastapi>=0.115.12",
    "mcp>=1.9.1",
    "pydantic>=2.11.4",
    "uvicorn>=0.34.2",
]
